- controller/registercontroller.php
- templates/admin.php
- templates/domains.php
- templates/register.php
I took the liberty to correct some strings so that the language is more correct
> Fix some strings and typos

- templates/form.php
Check for undefined variables/array indexes that may occur on token verification.
Fixes #111
> Fix PHP notices

- .travis.yml
- README.md
- util/corebridge.php
This PR adds missing tests and fixes for the compatible versions from the README:
- ownCloud: 9.1+
- Nextcloud: 9+
> Test all supported ownCloud/Nextcloud versions

- templates/message.php
This stops the double icon after registration.
> Update to message.php to stop double icon.

- css/style.css
> Submit button width should match form width

- .travis.yml
- appinfo/info.xml
> Update testing matrix and nextcloud requirements

- lib/Db/RegistrationMapper.php
- lib/Service/RegistrationService.php
- tests/Integration/Controller/RegisterControllerTest.php
- tests/Integration/Service/RegistrationServiceTest.php
> Objects are always passed by reference

- README.md
Removed OwnCloud Support and updated the minimum version of NextCloud. 
Reference: https://github.com/nextcloud/registration/pull/223
> Updated Supported Software

- lib/Db/Registration.php
- lib/Db/RegistrationMapper.php
> Use non-deprecated QBMapper 

- templates/admin.php
> Fix checkbox style in admin settings

- js/form.js
- templates/form.php
> Fix show password option

- templates/admin.php
- templates/domains.php
- templates/form.php
- templates/message.php
- templates/register.php
Fix #67 
cc @keunes (in case you are still on board as you reported the issue)
Forgot password | Register form (new)
---|---
> Add a "Back to login" link similar to the forgot password page

- lib/Service/MailService.php
- templates/email.newuser.disabled_html.php
- templates/email.newuser.disabled_plaintext.php
- templates/email.newuser_html.php
- templates/email.newuser_plaintext.php
- templates/email.validate_html.php
- templates/email.validate_plaintext.php
- tests/Integration/Controller/RegisterControllerTest.php
Don't mind the missing logo, that is because my fake development domain can not be resolved by thunderbird.
Before | After
---|---
> Move emails to IEmailTemplate

- templates/form/user.php
> Fix invalid route on form

- appinfo/info.xml
> Don't allow limiting to groups

- lib/Controller/RegisterController.php
- lib/Controller/SettingsController.php
- lib/Service/RegistrationService.php
- lib/Settings/RegistrationSettings.php
- templates/admin.php
- templates/form/email.php
- tests/Unit/Controller/RegisterControllerTest.php
> Make mail confirmation optional

- templates/admin.php
Reported at Transifex.
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>
> Changed grammar

- CHANGELOG.md
- appinfo/info.xml
- lib/Migration/Version0005Date20200710135953.php
- tests/Unit/Service/RegistrationServiceTest.php
> Fix compatibility with doctrine/dbal 3.0

- css/register-button.css
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>
> Fix registration button placement

- css/style.css
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>
> Fix submit button

- lib/Service/MailService.php
- lib/Service/RegistrationService.php
- tests/Unit/Service/RegistrationServiceTest.php
Ref https://github.com/nextcloud/server/blob/d9015a8c94bfd71fe484618a06d276701d3bf9ff/lib/public/ILogger.php#L41
> Move from ILogger to LoggerInterface

- templates/form/user.php
Fix #283 
cc @quadcube @hobbsecky  can you confirm?
> Fix registration with loginname field

- appinfo/info.xml
Unify the spelling in applications.
> l10n: Correct spelling

- lib/Controller/RegisterController.php
- lib/Events/AFormEvent.php
- lib/Events/PassedFormEvent.php
- lib/Events/ShowFormEvent.php
- lib/Events/ValidateFormEvent.php
- templates/form/email.php
- tests/Unit/Controller/RegisterControllerTest.php
> Terms of service integration

- CHANGELOG.md
- appinfo/info.xml
- Allow apps to hook into the registration flow, e.g. Terms of Service   [#293](https://github.com/nextcloud/registration/pull/293)
> Add changelog for 1.2.0

- lib/Controller/RegisterController.php
Inspired by https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/core/Controller/ClientFlowLoginController.php#L256-L258
> Fix registration with Talk iOS app

- composer.json
- tests/phpunit.xml
#311  breaks as it doesn't work with 7.2, but the composer file was missing the platform requirement
> Fix php requirements and phpunit

- .github/workflows/phpunit.yml
- lib/Controller/RegisterController.php
> Fix language of hint exceptions

- lib/AppInfo/Application.php
- lib/Listener/UserEnabledListener.php
- lib/Service/RegistrationService.php
- tests/Unit/Service/RegistrationServiceTest.php
> Send welcome email when enabled

- css/register-button.css
Color | Unfocused/Before | After
---|---|---
Dark blue (worst case) | ![Bildschirmfoto von 2022-02-22 16-51-45](https://user-images.githubusercontent.com/213943/155169876-cdacc61b-cde0-4a04-a6a4-7c8173534323.png) | ![Bildschirmfoto von 2022-02-22 16-51-42](https://user-images.githubusercontent.com/213943/155169882-d98236b2-5ad8-44b7-af93-56b916579c96.png)
Red | ![Bildschirmfoto von 2022-02-22 17-01-44](https://user-images.githubusercontent.com/213943/155171323-61a07964-e8b3-4a54-bbea-1952d0739980.png) | ![Bildschirmfoto von 2022-02-22 17-01-55](https://user-images.githubusercontent.com/213943/155171344-0a30d830-63f8-4404-9673-10176d879598.png)
Fix #391
> Fix missing focus feedback

- lib/RegistrationLoginOption.php
> Fix theming without darkmode when accessibility is not loaded

- .github/workflows/phpunit-sqlite.yml
> Update master target versions

- css/register-button.css
> Force button colors until 24 is the minimum

- lib/Controller/RegisterController.php
- package-lock.json
- templates/approval-required.php
- templates/form/email.php
- tests/Unit/Controller/RegisterControllerTest.php
Before | After
---|---
... | Ran NPM audit fix
> Fix minor things

- lib/Controller/RegisterController.php
- lib/Service/RegistrationService.php
- tests/Unit/Controller/RegisterControllerTest.php
- tests/Unit/Service/RegistrationServiceTest.php
> Allow spaces in allowed_domains config

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-sqlite.yml
> Adjust testing matrix for Nextcloud 25 on master

- lib/Service/MailService.php
> Fix admin email language

- .github/workflows/appstore-build-publish.yml
- .github/workflows/command-compile.yml
- .github/workflows/dependabot-approve-merge.yml
- .github/workflows/lint-eslint-when-unrelated.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node-when-unrelated.yml
- .github/workflows/node.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/phpunit-summary-when-unrelated.yml
- composer.json
> chore(CI): Update master php testing versions and workflow templates

- .github/workflows/phpunit-mysql.yml
- CHANGELOG.md
- appinfo/info.xml
- Compatibility with Nextcloud 26
- Send admin notification in correct language [#496](https://github.com/nextcloud/registration/pull/496)
> Release for 26

- CHANGELOG.md
- appinfo/info.xml
> bump version to 2.2.0

- .github/workflows/phpunit-mysql.yml
> chore(CI): Adjust testing matrix for Nextcloud 28 on master

- .github/workflows/phpunit-mysql.yml
- appinfo/info.xml
- package-lock.json
- package.json
> feat(deps): Add Nextcloud 29 support
